# Preface {.unnumbered}

<!-- This is a quarto book. To learn more about Quarto books visit <https://quarto.org/docs/books>. -->

Welcome to the diplotopia documentation!

## Pipeline status

This pipeline is currently under development.

It is possible that some tracks do not work as intended (eg. reorganisation modules, change of name). If you attempt to use this pipeline, please let us now if it not working or of anything that is weird (scientifically and bioinformatically).

You will can find "short" description of each track and its current the development status in @sec-overview.

## Reason for the development of this pipeline

The development of this pipeline started out to be able to analyze *Saprolegnia Parasitica* genetic data. The pipeline will (we hope) be further developed as other needs to study diploid organisms arise.

The purpose of the current track implemented in the pipeline is to help and guide the steps leading to variant calling on a poplation of diploid organism

-   do and determine what is the best assembly possible for a (diploid) organism you never worked with, previously (or not well studied). This means testing different assembly methods, to obtain the best possible assembly given the data at hand.
-   Choosing, cleaning and then using the best haploid assembly to detect variants within a population of genomes from the same species.

To do so we have developed several tracks (workflows), some of which might have different options (sub-workflows) that can be activated or deactivated.

## Statement of need

```{=html}
<!-- References 
The organization of this documentation and of this pipeline originates from [ALPPACA pipeline](https://github.com/NorwegianVeterinaryInstitute/ALPPACA) (at this stage)
-->
```